# -*- coding: utf-8 -*-

# Form implementation generated from reading ui file 'batpyqtgui.ui'
#
# Created by: PyQt5 UI code generator 5.4.1
#
# WARNING! All changes made in this file will be lost!

from PyQt5 import QtCore, QtGui, QtWidgets

class Ui_batpyqtgui(object):
    def setupUi(self, batpyqtgui):
        batpyqtgui.setObjectName("batpyqtgui")
        batpyqtgui.resize(1280, 720)
        self.centralwidget = QtWidgets.QWidget(batpyqtgui)
        self.centralwidget.setObjectName("centralwidget")
        self.gridlayout = QtWidgets.QGridLayout(self.centralwidget)
        self.gridlayout.setContentsMargins(9, 9, 9, 9)
        self.gridlayout.setSpacing(6)
        self.gridlayout.setObjectName("gridlayout")
        self.My_menu = QtWidgets.QMenuBar(self.centralwidget)
        self.My_menu.setGeometry(QtCore.QRect(0, 0, 135, 94))
        self.My_menu.setObjectName("My_menu")
        self.menu_file = QtWidgets.QMenu(self.My_menu)
        self.menu_file.setObjectName("menu_file")
        self.action_open = QtWidgets.QAction(batpyqtgui)
        icon = QtGui.QIcon()
        icon.addFile("document-open")
        self.action_open.setIcon(icon)
        self.action_open.setObjectName("action_open")
        self.action_test = QtWidgets.QAction(batpyqtgui)
        self.action_test.setObjectName("action_test")
        self.action_exit = QtWidgets.QAction(batpyqtgui)
        self.action_exit.setObjectName("action_exit")
        self.menu_edit = QtWidgets.QMenu(self.My_menu)
        self.menu_edit.setObjectName("menu_edit")
        self.action_find = QtWidgets.QAction(batpyqtgui)
        self.action_find.setObjectName("action_find")
        self.menu_configuration = QtWidgets.QMenu(self.My_menu)
        self.menu_configuration.setObjectName("menu_configuration")
        self.action_configation_open = QtWidgets.QAction(batpyqtgui)
        self.action_configation_open.setObjectName("action_configation_open")
        self.action_configation_filter = QtWidgets.QAction(batpyqtgui)
        self.action_configation_filter.setObjectName("action_configation_filter")
        self.action_configation_general = QtWidgets.QAction(batpyqtgui)
        self.action_configation_general.setObjectName("action_configation_general")
        self.actionA = QtWidgets.QAction(batpyqtgui)
        self.actionA.setObjectName("actionA")
        self.actionB = QtWidgets.QAction(batpyqtgui)
        self.actionB.setObjectName("actionB")
        self.gridlayout.addWidget(self.My_menu, 0, 0, 1, 3)
        self.splits = QtWidgets.QSplitter(self.centralwidget)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Expanding, QtWidgets.QSizePolicy.Expanding)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.splits.sizePolicy().hasHeightForWidth())
        self.splits.setSizePolicy(sizePolicy)
        self.splits.setObjectName("splits")
        self.widget = QtWidgets.QWidget(self.splits)
        self.widget.setObjectName("widget")
        self.verticalLayout = QtWidgets.QVBoxLayout(self.widget)
        self.verticalLayout.setContentsMargins(0, 0, 0, 0)
        self.verticalLayout.setObjectName("verticalLayout")
        self.FindArea = QtWidgets.QWidget(self.widget)
        self.FindArea.setObjectName("FindArea")
        self.nothing3 = QtWidgets.QHBoxLayout(self.FindArea)
        self.nothing3.setContentsMargins(0, 0, 0, 0)
        self.nothing3.setObjectName("nothing3")
        self.label_3 = QtWidgets.QLabel(self.FindArea)
        self.label_3.setObjectName("label_3")
        self.nothing3.addWidget(self.label_3)
        self.find = QtWidgets.QLineEdit(self.FindArea)
        self.find.setObjectName("find")
        self.nothing3.addWidget(self.find)
        self.closeFindAreaButton = QtWidgets.QPushButton(self.FindArea)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Fixed, QtWidgets.QSizePolicy.Fixed)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.closeFindAreaButton.sizePolicy().hasHeightForWidth())
        self.closeFindAreaButton.setSizePolicy(sizePolicy)
        self.closeFindAreaButton.setObjectName("closeFindAreaButton")
        self.nothing3.addWidget(self.closeFindAreaButton)
        self.verticalLayout.addWidget(self.FindArea)
        self.tree = QtWidgets.QTreeView(self.widget)
        self.tree.setObjectName("tree")
        self.verticalLayout.addWidget(self.tree)
        self.action_show_find_area = QtWidgets.QAction(batpyqtgui)
        self.action_show_find_area.setObjectName("action_show_find_area")
        self.web = QtWebKitWidgets.QWebView(self.splits)
        self.web.setObjectName("web")
        self.gridlayout.addWidget(self.splits, 1, 0, 100, 3)
        batpyqtgui.setCentralWidget(self.centralwidget)
        self.menubar = QtWidgets.QMenuBar(batpyqtgui)
        self.menubar.setGeometry(QtCore.QRect(0, 0, 560, 26))
        self.menubar.setObjectName("menubar")
        batpyqtgui.setMenuBar(self.menubar)
        self.statusbar = QtWidgets.QStatusBar(batpyqtgui)
        self.statusbar.setObjectName("statusbar")
        batpyqtgui.setStatusBar(self.statusbar)
        self.menu_file.addAction(self.action_open)
        self.menu_file.addAction(self.action_exit)
        self.menu_edit.addAction(self.action_find)
        self.menu_configuration.addAction(self.action_configation_open)
        self.menu_configuration.addAction(self.action_configation_general)
        self.menu_configuration.addAction(self.action_configation_filter)
        self.My_menu.addAction(self.menu_file.menuAction())
        self.My_menu.addAction(self.menu_edit.menuAction())
        self.My_menu.addAction(self.menu_configuration.menuAction())

        self.retranslateUi(batpyqtgui)
        self.action_open.triggered.connect(batpyqtgui.onOpenFile)
        self.action_exit.triggered.connect(batpyqtgui.close)
        self.action_configation_filter.triggered.connect(batpyqtgui.onOpenFilterDialog)
        self.action_configation_open.triggered.connect(batpyqtgui.onConfigurationOpen)
        self.action_find.triggered.connect(self.FindArea.show)
        self.action_find.triggered.connect(self.find.setFocus)
        self.closeFindAreaButton.pressed.connect(self.FindArea.hide)
        self.closeFindAreaButton.pressed.connect(batpyqtgui.onFindClosed)
        QtCore.QMetaObject.connectSlotsByName(batpyqtgui)

    def retranslateUi(self, batpyqtgui):
        _translate = QtCore.QCoreApplication.translate
        batpyqtgui.setWindowTitle(_translate("batpyqtgui", "Binary Analysis Tool 2015 Interface"))
        self.menu_file.setTitle(_translate("batpyqtgui", "File"))
        self.action_open.setText(_translate("batpyqtgui", "Open"))
        self.action_open.setShortcut(_translate("batpyqtgui", "Ctrl+O"))
        self.action_test.setText(_translate("batpyqtgui", "Test"))
        self.action_exit.setText(_translate("batpyqtgui", "Quit"))
        self.action_exit.setShortcut(_translate("batpyqtgui", "Ctrl+Q"))
        self.menu_edit.setTitle(_translate("batpyqtgui", "Edit"))
        self.action_find.setText(_translate("batpyqtgui", "Find"))
        self.action_find.setShortcut(_translate("batpyqtgui", "Ctrl+F"))
        self.menu_configuration.setTitle(_translate("batpyqtgui", "Configuration"))
        self.action_configation_open.setText(_translate("batpyqtgui", "Open Configration"))
        self.action_configation_filter.setText(_translate("batpyqtgui", "Filter Configration"))
        self.action_configation_general.setText(_translate("batpyqtgui", "General Configration (FIXME)"))
        self.actionA.setText(_translate("batpyqtgui", "a"))
        self.actionB.setText(_translate("batpyqtgui", "b"))
        self.label_3.setText(_translate("batpyqtgui", "Find"))
        self.closeFindAreaButton.setText(_translate("batpyqtgui", "X"))
        self.action_show_find_area.setText(_translate("batpyqtgui", "Find..."))
        self.action_show_find_area.setShortcut(_translate("batpyqtgui", "Ctrl+F"))

from PyQt5 import QtWebKitWidgets
